# Generated by Django 4.1.7 on 2023-03-15 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irrigationapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='junior',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='irrigationapp.jengineer'),
        ),
        migrations.AlterField(
            model_name='project',
            name='overseer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='irrigationapp.overseer'),
        ),
        migrations.AlterField(
            model_name='project',
            name='senior',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='irrigationapp.sengineer'),
        ),
    ]
