# Generated by Django 4.1.7 on 2023-03-15 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irrigationapp', '0002_alter_project_junior_alter_project_overseer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundrequest',
            name='eDate',
        ),
    ]
