# Generated by Django 4.1.1 on 2023-04-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigationapp', '0003_remove_fundrequest_edate'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
