# Generated by Django 5.1.4 on 2025-03-03 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigationapp', '0006_irrigationofficer_farmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('response', models.CharField(default='Pending', max_length=100)),
                ('responseDate', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('farmer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='irrigationapp.farmer')),
                ('officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='irrigationapp.irrigationofficer')),
            ],
        ),
    ]
