# Generated by Django 5.1.4 on 2025-03-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigationapp', '0007_farmercomplaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='land',
            field=models.FileField(upload_to=''),
        ),
    ]
