# Generated by Django 5.1.4 on 2025-03-03 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irrigationapp', '0008_alter_farmer_land'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irrigationofficer',
            name='rank',
        ),
    ]
